services:
  # Base de données MariaDB de test (image personnalisée)
  mariadb:
    image: cardmanager-mariadb-test:latest
    container_name: mariadb-test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dev
      MYSQL_USER: ia
      MYSQL_PASSWORD: foufafou
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  # Service Mason
  mason:
    build:
      context: .
      dockerfile: docker/mason/Dockerfile
    container_name: mason-test
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/dev
      - SPRING_DATASOURCE_USERNAME=ia
      - SPRING_DATASOURCE_PASSWORD=foufafou
      - SPRING_PROFILES_ACTIVE=test
    networks:
      - app-network

  # Service Painter
  painter:
    build:
      context: .
      dockerfile: docker/painter/Dockerfile
    container_name: painter-test
    ports:
      - "8081:8081"
    depends_on:
      mariadb:
        condition: service_healthy
      mason:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/dev
      - SPRING_DATASOURCE_USERNAME=ia
      - SPRING_DATASOURCE_PASSWORD=foufafou
      - SPRING_PROFILES_ACTIVE=test
      - PAINTER_IMAGE_STORAGE_PATH=/app/images
    volumes:
      - painter_images:/app/images
    networks:
      - app-network

  # Service GestionCarte
  gestioncarte:
    build:
      context: .
      dockerfile: docker/gestioncarte/Dockerfile
    container_name: gestioncarte-test
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
      painter:
        condition: service_started
      mason:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/dev
      - SPRING_DATASOURCE_USERNAME=ia
      - SPRING_DATASOURCE_PASSWORD=foufafou
      - SPRING_PROFILES_ACTIVE=test
      - PAINTER_SERVICE_URL=http://painter:8081
      - SPRING_LIQUIBASE_ENABLED=false
    networks:
      - app-network

volumes:
  painter_images:

networks:
  app-network:
    driver: bridge